### ISSUE TITLE
Error Creating a multiple

### ISSUE THREAD

**Issue by zeeshan-rasool-index** [haiyangwu/mediasoup-demo-android#11]
Error Creating a consumer: Failed to set remote offer sdk: Duplicate a=mid value'2'
i am using Android Device and Multiple browsers Firefox, safari, chrome.

on 1 to 1 it is working fine but when i am trying to connect multiple devices it is not working. i am not able to see videos of multiple user.

**Comment by YangZhouYz** [comment]
I have the same problem. Have you solved it?

**Comment by zeeshanrasool91** [comment]
no luck.. still waiting to get a response from them

**Comment by haiyangwu** [comment]
dup, https://github.com/haiyangwu/mediasoup-client-android/issues/23

**Comment by YangZhouYz** [comment]
&nbsp;&nbsp;
&nbsp; &nbsp; I reduced the version to 3.0.4-beta-2, but I haven't found any problems yet


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zeeshan rasool"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 下午3:08
收件人:&nbsp;"haiyangwu/mediasoup-demo-android"<mediasoup-demo-android@noreply.github.com&gt;;
抄送:&nbsp;"你"<1599914503@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [haiyangwu/mediasoup-demo-android] Error Creating a multiple (#11)





 
no luck.. still waiting to get a response from them
