### ISSUE TITLE
how can i excute this demo properly?

### ISSUE THREAD

**Issue by Snotra-p** [haiyangwu/mediasoup-demo-android#12]
Hello, I am a student studying.

I want to make a webrtc Android app using media soup.

But in this sample app, it seems like it's connected to the user itself, but nothing appears on the screen.

I am asking for help because I can't figure out which part to fix. Thank you.

**Comment by haiyangwu** [comment]
This is a demo connect to https://v3demo.mediasoup.org/，try to join the same room.
