### ISSUE TITLE
Websocket disconnected

### ISSUE THREAD

**Issue by jajangjayus** [haiyangwu/mediasoup-demo-android#13]
I'm trying this demo, I change HOSTNAME into my own mediasoup server then running to my Device and Websocket disconnected appear, how do i fixed it?

**Comment by hoangvuanhdevelopervn** [comment]
I have the same problem, did you fixed this problem?

**Comment by haiyangwu** [comment]
This is a  demo project.  keeping WebSocket connection is out of the scope. pls try to solve this deps on your project.

**Comment by ravithejappl** [comment]
@jajangjayus @hoangvuanhdevelopervn  did you find any solution for this?
