### ISSUE TITLE
VP9 i am posting vidoe streaming output was H264

### ISSUE THREAD

**Issue by balajinammalvar** [haiyangwu/mediasoup-demo-android#15]
I am using this in android native app url i post in app 4443/?roomId=yhj3knsh&peerId=ryqxw6oc&forceVP9=true but in video streaming codec was H264 in web i was posting forceVP9= true why this error came please resolve this.... is this error came before in android for anyone pls help me out @haiyangwu

**Comment by haiyangwu** [comment]
Video Codec can be configured in the settings activity.
