### ISSUE TITLE
App toast message ‘Could not join the room, internal error’ in roomclient sometimes

### ISSUE THREAD

**Issue by cl767234006** [haiyangwu/mediasoup-demo-android#18]
Put my network is shutdown,my protoo connect is failed,and when my network get well,sometime toast show  ‘Could not join the room, internal error’ and close connect.【测试断网重连机制，当网络断开再次恢复后，有时会报错在发送 join 命令时】     
                      
android log(客户端日志)：
W/Peer: request() createWebRtcTransport fail, 500, 500
W/System.err: org.protoojs.droid.ProtooException
W/System.err:     at org.mediasoup.droid.lib.Protoo.syncRequest(Protoo.java:80)
        at org.mediasoup.droid.lib.Protoo.syncRequest(Protoo.java:70)
        at org.mediasoup.droid.lib.RoomClient.createSendTransport(RoomClient.java:900)
W/System.err:     at org.mediasoup.droid.lib.RoomClient.joinImpl(RoomClient.java:674)
        at org.mediasoup.droid.lib.RoomClient.access$500(RoomClient.java:38)
        at org.mediasoup.droid.lib.RoomClient$2.lambda$onOpen$0$RoomClient$2(RoomClient.java:574)
W/System.err:     at org.mediasoup.droid.lib.-$$Lambda$RoomClient$2$1yrKTPoWaRxWuD7Kk1QcDNV7v7Y.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err:     at android.os.Looper.loop(Looper.java:237)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)

mediasoup server log(服务器端日志)：
  mediasoup-demo-server:INFO protoo connection request [roomId:101, peerId:lojt2nfi, address:183.185.216.161, origin:undefined] +21s
  mediasoup-demo-server:WARN:Room handleProtooConnection() | there is already a protoo Peer with same peerId, closing it [peerId:lojt2nfi] +34m
  mediasoup-demo-server:INFO:Room last Peer in the room left, closing the room [roomId:101] +21s
  protoo-server:ERROR:WebSocketTransport connection "error" event [conn:WSS:[183.185.216.161]:34888, error:Error: read ECONNRESET] +22s
  mediasoup:ERROR:Channel [pid:2665 Worker::GetRouterFromRequest() | throwing MediaSoupError: Router not found +34m
  mediasoup:WARN:Channel request failed [method:router.createWebRtcTransport, id:277]: Router not found +35s
  mediasoup-demo-server:ERROR:Room request failed:Error: Router not found at Channel._processMessage (/usr/local/webrtc/mediasoup/mediasoup-demo/server/node_modules/mediasoup/lib/Channel.js:206:37) at Socket.Channel._consumerSocket.on (/usr/local/webrtc/mediasoup/mediasoup-demo/server/node_modules/mediasoup/lib/Channel.js:68:34) at Socket.emit (events.js:182:13) at Socket.EventEmitter.emit (domain.js:441:20) at addChunk (_stream_readable.js:283:12) at readableAddChunk (_stream_readable.js:264:11) at Socket.Readable.push (_stream_readable.js:219:10) at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) +34m

**Comment by haiyangwu** [comment]
dup https://github.com/haiyangwu/mediasoup-demo-android/issues/13
