### ISSUE TITLE
Sound volume is too low.

### ISSUE THREAD

**Issue by ramunl** [haiyangwu/mediasoup-demo-android#19]
Tested on Xiami 5s (andr.8.0)

Video stream works great but the sound is almost not hearable.  It works via phone speaker, how can I switch the audio output to the loud speaker?

**Comment by Ben0421** [comment]
This is not specific to this demo but to Android. I recommend checking first if a wired headset is present. This will make the _device_ use the speakerphone, regardless of whether a Bluetooth headset is plugged in or a wired headset is plugged in or in use.

`
this.audioManager = (AudioManager) applicationContext.getSystemService(Context.AUDIO_SERVICE);
audioManager.setSpeakerphoneOn(true);
`

**Comment by ramunl** [comment]
Thanks for your clarification. The problem solved.

**Comment by hoangvuanh761993** [comment]
@ramunl hello, Did you fix this problem and how did you do it?

**Comment by haiyangwu** [comment]
@Ben0421 Thx, close this issuse
