### ISSUE TITLE
Can not Use H264 Codec

### ISSUE THREAD

**Issue by madzheng** [haiyangwu/mediasoup-demo-android#21]
When I enable the forceH264 button, the app can not see other peer's view. So I think maybe there is something wrong with the app about H264 codec. Comparing other codec,  the H264 is more professional.
How can I solve the problem?

**Comment by haiyangwu** [comment]
The default impl of h264 is deps on hardware, if this is the root cause of this issue, you can change the source code of webrtc (add software impl of h264)
