### ISSUE TITLE
No implementation found for void org.webrtc.voiceengine.WebRtcAudioRecord.nativeDataIsRecorded(int, long)

### ISSUE THREAD

**Issue by leo-wxy** [haiyangwu/mediasoup-demo-android#23]
- System version：6.0.1 (API 23)
- CPU_ABI：armeabi-v7a

- Log：
```
09-07 10:36:59.053 28998-29191/org.mediasoup.droid.demo E/art: No implementation found for void org.webrtc.voiceengine.WebRtcAudioRecord.nativeDataIsRecorded(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioRecord_nativeDataIsRecorded and Java_org_webrtc_voiceengine_WebRtcAudioRecord_nativeDataIsRecorded__IJ)
09-07 10:36:59.053 28998-29191/org.mediasoup.droid.demo E/AndroidRuntime: FATAL EXCEPTION: AudioRecordJavaThread
    Process: org.mediasoup.droid.demo, PID: 28998
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioRecord.nativeDataIsRecorded(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioRecord_nativeDataIsRecorded and Java_org_webrtc_voiceengine_WebRtcAudioRecord_nativeDataIsRecorded__IJ)
        at org.webrtc.voiceengine.WebRtcAudioRecord.nativeDataIsRecorded(Native Method)
        at org.webrtc.voiceengine.WebRtcAudioRecord.access$600(WebRtcAudioRecord.java:26)
        at org.webrtc.voiceengine.WebRtcAudioRecord$AudioRecordThread.run(WebRtcAudioRecord.java:166)
09-07 10:36:59.173 28998-29098/org.mediasoup.droid.demo E/RoomClient: joinRoom() failed:
09-07 10:36:59.173 28998-29098/org.mediasoup.droid.demo E/RoomClient: org.protoojs.droid.ProtooException
09-07 10:36:59.173 28998-29098/org.mediasoup.droid.demo E/RoomClient: org.protoojs.droid.ProtooException
        at org.mediasoup.droid.lib.Protoo.syncRequest(Protoo.java:80)
        at org.mediasoup.droid.lib.Protoo.syncRequest(Protoo.java:70)
        at org.mediasoup.droid.lib.RoomClient.createSendTransport(RoomClient.java:890)
        at org.mediasoup.droid.lib.RoomClient.joinImpl(RoomClient.java:674)
        at org.mediasoup.droid.lib.RoomClient.access$500(RoomClient.java:38)
        at org.mediasoup.droid.lib.RoomClient$2.lambda$onOpen$0$RoomClient$2(RoomClient.java:574)
        at org.mediasoup.droid.lib.-$$Lambda$RoomClient$2$1yrKTPoWaRxWuD7Kk1QcDNV7v7Y.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by yinbiaos** [comment]
i have get the same error, did you have any idea?

**Comment by leo-wxy** [comment]
> i have get the same error, did you have any idea?

你可以试试重新编译对应的mediasoup-client-android，我是后来编译之后，直接集成就没问题了。应该是依赖的有问题

**Comment by acoderleex** [comment]
> > i have get the same error, did you have any idea?
> 
> 你可以试试重新编译对应的mediasoup-client-android，我是后来编译之后，直接集成就没问题了。应该是依赖的有问题

大佬有对应的编译教程吗

**Comment by leo-wxy** [comment]
> > > i have get the same error, did you have any idea?
> > 
> > 
> > 你可以试试重新编译对应的mediasoup-client-android，我是后来编译之后，直接集成就没问题了。应该是依赖的有问题
> 
> 大佬有对应的编译教程吗

我是基于Ubuntu 18.04版本进行编译的

### 编译webrtc

```shell
//编译工具下载
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATh="$PATH:${HOME}/depot_tools" //配置环境变量

//下载webrtc源码
mkdir webrtc_android
cd webrtc_android
git clone https://webrtc.googlesource.com/src
fetch --nohooks webrtc_android
gclient sync

//编译webrtc源码
cd src
./build/install-build-deps.sh

gn gen out/Debug --args='target_os="android" target_cpu="arm"'
// gn gen out/Release --args='is_debug=false is_component_build=false rtc_include_tests=false target_os="android" target_cpu="arm"'

autoninja -C out/Debug
//autoninja -C out/Release
```

对应文件输出目录：

./out/Debug/lib_java/sdk/android/libwebrtc.jar 

./out/Debug/libjingle_peerconnection_so.so

上面这俩是Android需要用到的sdk

./out/Debug/lib.unstripped/libjingle_peerconnection_so.so

./out/Debug/obj/libwebrtc.a //静态链接

### 编译libmediasoupclient

#### 下载代码

git clone https://github.com/versatica/libmediasoupclient

cd libmediasoupclient/

#### 编译配置

```shell
cmake . -Bbuild \
-DLIBWEBRTC_INCLUDE_PATH:PATH=PATH_TO_LIBWEBRTC_SOURCES \     # src源代码目录
-DLIBWEBRTC_BINARY_PATH:PATH=PATH_TO_LIBWEBRTC_BINARY         # 编译出libwebrtc.a目录
```

示例配置

cmake . -Bbuild   -DLIBWEBRTC_INCLUDE_PATH:PATH=/home/zaze/Desktop/webrtc_android/src   -DLIBWEBRTC_BINARY_PATH:PATH=/home/XXX/Desktop/webrtc_android/src/out/Debug/obj

运行命令后，再执行

```shell
make -C build/
```

在`./build/`目录下会生成`libmediasoupclient.a`文件取出备用



### 获取libmediasoupclient sdk

基于[mediasoup-client-android](https://github.com/haiyangwu/mediasoup-client-android)进行编译，注意以下关键点：

- clone后的项目里面的`mediasoup-client/deps/webrtc/lib`里面的`libwebrtc.a`文件都是有误的，需要从`https://github.com/haiyangwu/webrtc-android-build`获取对应版本的文件，下载完成后替换原有的`libs`目录

我是基于Ubuntu 18.04进行编译的

**Comment by acoderleex** [comment]
> > > > i have get the same error, did you have any idea?
> > > 
> > > 
> > > 你可以试试重新编译对应的mediasoup-client-android，我是后来编译之后，直接集成就没问题了。应该是依赖的有问题
> > 
> > 
> > 大佬有对应的编译教程吗
> 
> 我是基于Ubuntu 18.04版本进行编译的
> 
> ### 编译webrtc
> ```shell
> //编译工具下载
> git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
> export PATh="$PATH:${HOME}/depot_tools" //配置环境变量
> 
> //下载webrtc源码
> mkdir webrtc_android
> cd webrtc_android
> git clone https://webrtc.googlesource.com/src
> fetch --nohooks webrtc_android
> gclient sync
> 
> //编译webrtc源码
> cd src
> ./build/install-build-deps.sh
> 
> gn gen out/Debug --args='target_os="android" target_cpu="arm"'
> // gn gen out/Release --args='is_debug=false is_component_build=false rtc_include_tests=false target_os="android" target_cpu="arm"'
> 
> autoninja -C out/Debug
> //autoninja -C out/Release
> ```
> 
> 对应文件输出目录：
> 
> ./out/Debug/lib_java/sdk/android/libwebrtc.jar
> 
> ./out/Debug/libjingle_peerconnection_so.so
> 
> 上面这俩是Android需要用到的sdk
> 
> ./out/Debug/lib.unstripped/libjingle_peerconnection_so.so
> 
> ./out/Debug/obj/libwebrtc.a //静态链接
> 
> ### 编译libmediasoupclient
> #### 下载代码
> git clone https://github.com/versatica/libmediasoupclient
> 
> cd libmediasoupclient/
> 
> #### 编译配置
> ```shell
> cmake . -Bbuild \
> -DLIBWEBRTC_INCLUDE_PATH:PATH=PATH_TO_LIBWEBRTC_SOURCES \     # src源代码目录
> -DLIBWEBRTC_BINARY_PATH:PATH=PATH_TO_LIBWEBRTC_BINARY         # 编译出libwebrtc.a目录
> ```
> 
> 示例配置
> 
> cmake . -Bbuild -DLIBWEBRTC_INCLUDE_PATH:PATH=/home/zaze/Desktop/webrtc_android/src -DLIBWEBRTC_BINARY_PATH:PATH=/home/XXX/Desktop/webrtc_android/src/out/Debug/obj
> 
> 运行命令后，再执行
> 
> ```shell
> make -C build/
> ```
> 
> 在`./build/`目录下会生成`libmediasoupclient.a`文件取出备用
> 
> ### 获取libmediasoupclient sdk
> 基于[mediasoup-client-android](https://github.com/haiyangwu/mediasoup-client-android)进行编译，注意以下关键点：
> 
> * clone后的项目里面的`mediasoup-client/deps/webrtc/lib`里面的`libwebrtc.a`文件都是有误的，需要从`https://github.com/haiyangwu/webrtc-android-build`获取对应版本的文件，下载完成后替换原有的`libs`目录
> 
> 我是基于Ubuntu 18.04进行编译的

THX.我倒是编译出来了四个版本的libmediasoupclient.a文件，但是基于mediasoup-client-android进行编译这个不清楚怎么改造了，大佬能否再次不吝赐教

**Comment by haiyangwu** [comment]
ref: https://github.com/haiyangwu/mediasoup-client-android/blob/dev/mediasoup-client/CMakeLists.txt
