### ISSUE TITLE
 audio stream

### ISSUE THREAD

**Issue by ChinaLiuKang** [haiyangwu/mediasoup-demo-android#26]
Hello, I have carried out secondary development of the project and changed the way of video streaming to get from the recording screen, but how do I input the audio stream into the mediasoup Android client? Currently I can get the byte data of the audio stream

**Comment by ChinaLiuKang** [comment]
Baby blogger where have you been !!!!

**Comment by haiyangwu** [comment]
Try to impl your AudioSource, and use this fucntion in `org.webrtc.PeerConnectionFactory`
```
  public AudioTrack createAudioTrack(String id, AudioSource source) {
    checkPeerConnectionFactoryExists();
    return new AudioTrack(nativeCreateAudioTrack(nativeFactory, id, source.getNativeAudioSource()));
  }
```
