### ISSUE TITLE
Mic from android very low

### ISSUE THREAD

**Issue by Bengua27** [haiyangwu/mediasoup-demo-android#31]
Hello,

Thank you very much for sharing this demo app.
We are meeting one issue with this demo app on real devices. The sound level of the mic is very low.

Sound level:
- from Chrome to android phone (after enabling speaker) -> OK
- from android phone to Chrome -> Not OK. it's very low. we have tried different phones (google pixel and samsung phones)

@haiyangwu any idea why ?
Thanks a lot

**Comment by haiyangwu** [comment]
It's maybe related to AEC, try to disable it
