### ISSUE TITLE
android terminal is not flow

### ISSUE THREAD

**Issue by cl767234006** [haiyangwu/mediasoup-demo-android#7]
throw test,android terminal is not flow,i guess it may be because pixel is too high.I try to control send bitrate size,but not effect.
`String codecOptions ="[\r\n" + "{\r\n" + "\"videoGoogleStartBitrate\": \"1000\"\r\n"   + "},\r\n"
              + "{\r\n" + "\"videoGoogleMaxBitrate\": \"600\"\r\n"   + "},\r\n"
              + "{\r\n" + "\"videoGoogleMinBitrate\": \"1500\"\r\n"   + "}\r\n"
              +  "]";

      mCamProducer =
          mSendTransport.produce(
              producer -> {
                Logger.e(TAG, "onTransportClose(), camProducer");
                if (mCamProducer != null) {
                  mStore.removeProducer(mCamProducer.getId());
                  mCamProducer = null;
                }
              },
              mLocalVideoTrack,
              null,
//                  codecOptions);
              null);`

**Comment by haiyangwu** [comment]
"not flow"？ What is the exact meaning?
