### ISSUE TITLE
App crash when enter the room after exit room fatal error!

### ISSUE THREAD

**Issue by james133** [haiyangwu/mediasoup-demo-android#8]
It is recommended to give priority to repair, otherwise it cannot be productized !

# AudioTrackJavaThread(6741)

java.lang.UnsatisfiedLinkError

No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)

**Comment by haiyangwu** [comment]
duplicate with https://github.com/haiyangwu/mediasoup-client-android/issues/12
