### ISSUE TITLE
如何更改为H264编码

### ISSUE THREAD

**Issue by luweiandzhangman** [haiyangwu/mediasoup-demo-android#9]
目前运行起来默认是vp8的,如何更改为H264编码

**Comment by haiyangwu** [comment]
请看一下 Demo 的设置界面逻辑

**Comment by luweiandzhangman** [comment]
你好,很感谢您的回复.目前出现的问题是服务器切换为H264后,两个人A在安卓手机和B在pc进行通话,A本地视频能看到,A看不到B但能听到B的声音,B显示完全正常,这个问题解决不了,还请帮忙,谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "haiyangwu"; 
发送时间: 2020年4月22日(星期三) 下午2:25
收件人: "haiyangwu/mediasoup-demo-android";
抄送: "luwei"<404474566@qq.com>;"Author";
主题: Re: [haiyangwu/mediasoup-demo-android] 如何更改为H264编码 (#9)





 
请看一下 Demo 的设置界面逻辑
 
&mdash;

**Comment by madzheng** [comment]
> 你好,很感谢您的回复.目前出现的问题是服务器切换为H264后,两个人A在安卓手机和B在pc进行通话,A本地视频能看到,A看不到B但能听到B的声音,B显示完全正常,这个问题解决不了,还请帮忙,谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "haiyangwu"; 发送时间: 2020年4月22日(星期三) 下午2:25 收件人: "haiyangwu/mediasoup-demo-android"; 抄送: "luwei"<404474566@qq.com>;"Author"; 主题: Re: [haiyangwu/mediasoup-demo-android] 如何更改为H264编码 (#9) 请看一下 Demo 的设置界面逻辑 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我也遇到了相同的问题，就是安卓端无法通过H264进行编解码，forceH264开启后，看不到对面的视频。请问您解决这个问题了吗？

**Comment by madzheng** [comment]
> 请看一下 Demo 的设置界面逻辑

forceH264打开后，强制使用H264进行编解码的话，看不到对面的画面。我也遇到这个问题了。请问有没有解决这个问题的方案？

**Comment by chenjim** [comment]
我已解决，详细可参考 https://blog.csdn.net/CSqingchen/article/details/120199702
